### ISSUE TITLE
Issues - Ubuntu 15

### ISSUE THREAD

**Issue by dereuromark** [spryker/devvm#10] opened 2016-03-07 11:48 UTC
I cannot install the new vm on linux, several issues

```
Installing the Window System drivers
Could not find the X.Org or XFree86 Window System, skipping.
An error occurred during installation of VirtualBox Guest Additions 5.0.16. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
stdin: is not a tty

```
The later in the process

```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.60.1:'/home/mark/git/devvmtest/demoshop' /data/shop/development/current

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 192.168.60.1:/home/mark/git/devvmtest/demos
```

vagrant 1.8.1
VBox 5.0.16

**Comment by marek-obuchowicz** [comment] 2016-03-07 12:06
hmmm looks like vagrant somehow fails to prepare exports... what's in your `/etc/exports` file? what's status of `service nfs-kernel-server status`? Does it change if you do `service nfs-kernel-server restart` ? Is there any useful information in `/var/log/daemon.log` or `/var/log/messages` or `/var/log/syslog` ?

**Comment by dereuromark** [comment] 2016-03-07 13:47
In there:
```
# VAGRANT-BEGIN: 1000 fe0dd0b2-d2a9-401f-bbb0-f9ab873e74a9
...
"/home/mark/git/devvmtest/demoshop" 10.10.0.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=20586$
# VAGRANT-END: 1000 53515398-48e1-4d0f-b4ed-395c43af8d18
```

service nfs-kernel-server status:
```
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Mi 2016-03-02 16:16:55 CET; 4 days ago
 Main PID: 946 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Mär 02 16:16:55 mark-tp-office systemd[1]: Starting NFS server and services...
Mär 02 16:16:55 mark-tp-office systemd[1]: Started NFS server and services.
```

After restart:
```
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Mo 2016-03-07 14:42:00 CET; 2s ago
  Process: 20610 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCESS)
  Process: 20609 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCESS)
  Process: 20607 ExecStop=/usr/sbin/rpc.nfsd 0 (code=exited, status=0/SUCCESS)
  Process: 20625 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 20622 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 20625 (code=exited, status=0/SUCCESS)

Mär 07 14:42:00 mark-tp-office systemd[1]: Starting NFS server and services...
Mär 07 14:42:00 mark-tp-office systemd[1]: Started NFS server and services.
```

var/log/syslog contains sth but does not seem to related.

I will now try `vagrant up --provision` again.

**Comment by marek-obuchowicz** [comment] 2016-03-07 13:50
The line in /etc/exports:
```
"/home/mark/git/devvmtest/demoshop" 10.10.0.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=20586$
```
looks definitely bad. The `$` sign ad the end of the line shouldn't be there and the bracket `(` is not closed.  Can you confirm that it's not a copy/paste error?

**Comment by dereuromark** [comment] 2016-03-07 13:53
Sry, you are right, EOL of the window made this, the full line is

    "/home/mark/git/devvmtest/demoshop" 10.10.0.33(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=2058667293)

**Comment by dereuromark** [comment] 2016-03-07 14:27
So after fresh up with provision everything runs through without errors it seems.
But the page for frontend and backend still both output

    File not found.

Is there a trouble guide on what to add manually to hosts file etc in such a case?
What else does need to be done in these cases?

**Comment by dereuromark** [comment] 2016-03-07 14:48
OK, switching from dev-master to dev-develop and the brand new stuff with SPY there seems to work.

Only issue left is DB, and for Yves I get `504 Gateway Time-out`

probably because of
```
ZED Exception: Propel\Runtime\Exception\PropelException - SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "spy_touch_storage-unique-fk_locale"
DETAIL:  Key (fk_locale, key)=(66, de.en_us.resource.product_abstract.1) already exists.

Executed query: 
INSERT INTO "spy_touch_storage" ("id_touch_storage", "fk_locale", "fk_touch", "key") VALUES (365, 66, 345, 'de.en_us.resource.product_abstract.1')
in /data/shop/development/current/src/Orm/Zed/Touch/Persistence/Base/SpyTouchStorage.php (785)

Command: vendor%2Fbin%2Fconsole+collector%3Astorage%3Aexport+-vvv
```
//cc @spryker/core-development

**Comment by dereuromark** [comment] 2016-03-07 15:11
Still get a gateway timeout for Yves, even though the sql issues dont show up again and the setup process seemed to run though fine.

**Comment by lmanzke** [comment] 2016-03-07 15:22
Maybe it's the good old LOCK_EX again? :D

**Comment by dereuromark** [comment] 2016-03-07 15:31
Not again.. I will check

**Comment by dereuromark** [comment] 2016-03-07 16:36
Damn it, you are right.
It is the same issue as with the old VM, it is not built in a way that you can safely use LOCK_EX on it in any way.

I have to continue to use the hack

    $config[EventJournalConstants::LOCK_OPTIONS][EventJournalConstants::NO_LOCK] = true;

**Comment by sandries** [comment] 2016-03-08 15:34
Why we don't have this configuration by default? What does it do and why the installation on linux fails without this configuration?
It's a bit odd to have this entry in the configuration as a fix for this use case.

**Comment by dereuromark** [comment] 2016-03-08 15:36
Dont ask me :) It is some issue with how the vagrant machine does its internal ntfs mounting.
It is also only required for linux, so just add a small warning below to mention this is required for those OS in the config_local.php file.

**Comment by marek-obuchowicz** [comment] 2016-03-08 15:39
Instead of answering "why we don't have this configuration" by default, i'd rather suggest it to be the default (for development env) and to put it in `config_default_development.php`.
It disables file locking mechanism while writing logs. On production where we have multiple processes running on a machine at the same time it prevents entries to be corrupted, but for me - we can use it on development

**Comment by dereuromark** [comment] 2016-03-08 15:40
It is still just a workaround, we also have external tools that use LOCK_EX which will still fail hard because of this.
We must fix this, putting this as default will most likely put this into the background where it will get lost IMO.

**Comment by sandries** [comment] 2016-03-08 15:42
I agree with @dereuromark ; later you still hit on this problem and it's better to fail fast.

Thank you @marek-obuchowicz for the explanation.

**Comment by marek-obuchowicz** [comment] 2016-03-08 15:43
Well, we should try at least. Can you add "nolock" to Vagrantfile mount options (see last comment on https://github.com/thephpleague/flysystem/issues/445) and try?

**Comment by marek-obuchowicz** [comment] 2016-03-21 11:15
@dereuromark do we have any update on this?

**Comment by hhebbo** [comment] 2016-03-21 11:42
testing now

**Comment by vlunov-spryker** [comment] 2016-03-21 13:44
Confirmed, please add for NFS: 

`:mount_options => ['nolock'] `

**Comment by marek-obuchowicz** [comment] 2016-04-18 16:35
Fix is in https://github.com/spryker/devvm/releases/download/ci-70/spryker-devvm.box

**Closed by marek-obuchowicz** 2016-04-18 16:35 UTC
Labels: bug
