### ISSUE TITLE
2.x: Less confusing name for project

### ISSUE THREAD

**Issue by dereuromark** [spryker/devvm#47] opened 2017-12-04 10:26 UTC
In sync with `VM_PROJECT =         'project'`:

I would still recommend fixing the two options
```
SPRYKER_BRANCH =     'master'
SPRYKER_REPOSITORY = 'git@github.com:spryker/project.git'
```
to what they actually are:
```
VM_PROJECT_BRANCH
VM_PROJECT_REPOSITORY
```
(or without the VM_prefix)

**Comment by dereuromark** [comment] 2018-02-09 12:39
PROJECT_BRANCH and PROJECT_REPOSITORY should be short enough / fine.

**Comment by marek-obuchowicz** [comment] 2018-08-08 10:09
Duplicate of internal ticket - VM-18

**Closed by marek-obuchowicz** 2018-08-08 10:09 UTC
Labels: enhancement
